const constants = {
	SELECT_OPTIONS: {
		INCOME: {
			PAYMENT: ['CASH', 'CHEQUE', 'DD', 'UPI', 'BANK TRANSFER'],
		},
		EXPENDITURE: {
			PAYMENT: ['CASH', 'CHEQUE', 'DD', 'UPI', 'BANK TRANSFER'],
		},
	},
	SPREADSHEET: {
		ID: `${process.env.REACT_APP_GOOGLE_SPREAD_SHEET_ID}`,
	},
	FIREBASE: {
		apiKey: `${process.env.REACT_APP_FIREBASE_API_KEY}`,
		authDomain: `${process.env.REACT_APP_FIREBASE_AUTH_DOMAIN}`,
		projectId: `${process.env.REACT_APP_FIREBASE_PROJECT_ID}`,
		storageBucket: `${process.env.REACT_APP_FIREBASE_STORAGE_BUCKET}`,
		messagingSenderId: `${process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID}`,
		appId: `${process.env.REACT_APP_FIREBASE_APP_ID}`,
		measurementId: `${process.env.REACT_APP_FIREBASE_MEASURMENT_ID}`,
	},
	VALID_PHONES: ['8888888888', '9999999999'],
	SEX: ['MALE', 'FEMALE', 'OTHER'],
	BLOOD_GROUP: [
		'NOT KNOWN',
		'A+VE',
		'A-VE',
		'B+VE',
		'B-VE',
		'AB+VE',
		'AB-VE',
		'O+VE',
		'O-VE',
	],
	EMAIL_REGEX:
		/^(([^<>()[\].,;:\s@"]+(\.[^<>()[\].,;:\s@"]+)*)|(".+"))@(([^<>()[\].,;:\s@"]+\.)+[^<>()[\].,;:\s@"]{2,})$/i,
	DAYS_OF_WEEK: [
		{ 0: 'S' },
		{ 1: 'M' },
		{ 2: 'T' },
		{ 3: 'W' },
		{ 4: 'T' },
		{ 5: 'F' },
		{ 6: 'S' },
		{ 7: 'S' },
		{ 8: 'M' },
		{ 9: 'T' },
		{ 10: 'W' },
		{ 11: 'T' },
		{ 12: 'F' },
		{ 13: 'S' },
		{ 14: 'S' },
		{ 15: 'M' },
		{ 16: 'T' },
		{ 17: 'W' },
		{ 18: 'T' },
		{ 19: 'F' },
		{ 20: 'S' },
		{ 21: 'S' },
		{ 22: 'M' },
		{ 23: 'T' },
		{ 24: 'W' },
		{ 25: 'T' },
		{ 26: 'F' },
		{ 27: 'S' },
		{ 28: 'S' },
		{ 29: 'M' },
		{ 30: 'T' },
		{ 31: 'W' },
		{ 32: 'T' },
		{ 33: 'F' },
		{ 34: 'S' },
		{ 35: 'S' },
		{ 36: 'M' },
		{ 37: 'T' },
		{ 38: 'W' },
		{ 39: 'T' },
		{ 40: 'F' },
		{ 41: 'S' },
		{ 42: 'S' },
	],
	EXP_STATS: {
		APP: 'APPROVED',
		PEN: 'PENDING',
		DEL: 'DELETED',
	},
	USER_PERMS: {
		EXECUTIVE: 'executive',
		TREASURER: 'treasurer',
		MEMBER: 'member',
		TEST: 'test',
	},
	USER_TYPES: {
		PRESIDENT: 'PRESIDENT',
		SECRETARY: 'SECRETARY',
		TREASURER: 'TREASURER',
		MEMBER: 'MEMBER',
		DISCONTINUED: 'DISCONTINUED',
	},
};

export default constants;
